### PR TITLE
Upgrade to latest view-creation library and also updated others.

### PR DESCRIPTION
**Pull request by buchi-busireddy**
The latest view-creation library introduces some mandatory configs
in pinot view configs so added them as well.

### CODE REVIEW

**Review by aaron-steinfeld — DISMISSED** [review]

**Comment by buchi-busireddy** [comment]
FYI, Snyk failure is because we have hit our monthly quota for snyk jobs.

**Comment by aaron-steinfeld** [comment]
> FYI, Snyk failure is because we have hit our monthly quota for snyk jobs.

that's bad messaging on their part, its OSS so the quota doesn't apply. Scroll up in the logs and you'll see the snyk issues.

**Comment by buchi-busireddy** [comment]
> > FYI, Snyk failure is because we have hit our monthly quota for snyk jobs.
> 
> that's bad messaging on their part, its OSS so the quota doesn't apply. Scroll up in the logs and you'll see the snyk issues.

Oh wow.. thanks for pointing that. I've fixed the snyk failure now.

**Review by aaron-steinfeld — APPROVED** [review]

**Review by tim-mwangi — APPROVED** [review]

**Comment by tim-mwangi** [comment]
I'm guessing the snyk failures are because of pinot tools dependency. Are we going to ever report that to Pinot?

**Comment by buchi-busireddy** [comment]
> I'm guessing the snyk failures are because of pinot tools dependency. Are we going to ever report that to Pinot?

Good idea. We should report and if possible we can even fix them in the upstream so that in the next version we can get updates.

**Pull request merged**
